VivedyWebApp/Models/ViewModels/AdminRotationsViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace VivedyWebApp.Models.ViewModels
{
    /// <summary>
    /// Model specificly used for creating new Rotation on AdminRotations/Create page
    /// </summary>
    public class AdminRotationsCreateViewModel
    {
        /// <summary>
        /// Start day and time for the rotation
        /// </summary>
        [Display(Name = "Start Day and Time")]
        [Required]
        public System.DateTime StartTime { get; set; }

        /// <summary>
        /// ID of the movie for which the rotations is created
        /// </summary>
        [Display(Name = "Movie Id")]
        [ForeignKey("Movie")]
        [Required]
        public string MovieId { get; set; }
        public Movie Movie { get; set; }

        /// <summary>
        /// Boolean indicating whether a week of rotations is auto-generated
        /// </summary>
        [Display(Name = "Auto-generate a week of rotations?")]
        public bool GenerateRotations { get; set; }
    }
}

VivedyWebApp/Controllers/AdminRotationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VivedyWebApp.Models;
using VivedyWebApp.Models.ViewModels;

namespace VivedyWebApp.Controllers
{
    /// <summary>
    /// Application Admin Controller for Rotations
    /// </summary>
    public class AdminRotationsController : Controller
    {
        /// <summary>
        /// ApplicationDbContext instance
        /// </summary>
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// GET request action for Index page
        /// </summary>
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            return View(await db.Rotations.ToListAsync());
        }

        /// <summary>
        /// GET request action for Details page
        /// </summary>
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Rotation rotation = await db.Rotations.FindAsync(id);
            if (rotation == null)
            {
                return HttpNotFound();
            }
            return View(rotation);
        }

        /// <summary>
        /// GET request action for Create page
        /// </summary>
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST request action for Create page
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(AdminRotationsCreateViewModel newRotation)
        {
            if (ModelState.IsValid)
            {
                Rotation rotation = new Rotation
                {
                    RotationId = Guid.NewGuid().ToString(),
                    StartTime = newRotation.StartTime,
                    MovieId = newRotation.MovieId
                };
                db.Rotations.Add(rotation);
                //Generating rotations
                if (newRotation.GenerateRotations)
                {
                    for(int i = 1; i < 7; i++)
                    {
                        //A rotation for each day starting from the newRotation.StartTime at the same time of the day
                        Rotation autoRotation = new Rotation
                        {
                            RotationId = Guid.NewGuid().ToString(),
                            StartTime = newRotation.StartTime.AddDays(i),
                            MovieId = newRotation.MovieId
                        };
                        db.Rotations.Add(autoRotation);
                    }
                }
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(newRotation);
        }

        /// <summary>
        /// GET request action for Edit page
        /// </summary>
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rotation rotation = await db.Rotations.FindAsync(id);
            if (rotation == null)
            {
                return HttpNotFound();
            }
            return View(rotation);
        }

        /// <summary>
        /// POST request action for Edit page
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(Rotation rotation)
        {
            if (!ModelState.IsValid)
            {
                return View(rotation);
            }
            db.Entry(rotation).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// GET request action for Delete page
        /// </summary>
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rotation rotation = await db.Rotations.FindAsync(id);
            if (rotation == null)
            {
                return HttpNotFound();
            }
            return View(rotation);
        }

        /// <summary>
        /// POST request action for DeleteConfirmed page
        /// </summary>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Rotation rotation = await db.Rotations.FindAsync(id);
            db.Rotations.Remove(rotation);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Method for disposing ApplicationDbContext objects
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VivedyWebApp/Views/AdminRotations/Create.cshtml
@model VivedyWebApp.Models.ViewModels.AdminRotationsCreateViewModel

@{
    ViewBag.Title = "Admin | Create Rotation";
}

@using (Html.BeginForm("Create", "AdminRotations", null, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="containerOneAdmin">
        <div class="white-bg-color mx-auto text-dark " style="max-width: 750px; border: 0.5rem solid #a8000a;">
            <div class="mb-5 mt-4 phenomena-sm border-bottom border-dark " style="color: #a8000a"><h1 class="display-5">ADD ROTATION</h1></div>
            <div class="border-bottom">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-3 phenomena-sm">@Html.LabelFor(model => model.StartTime) :</div>
                    <div class="mb-3 col-md-8 phenomena-sm">
                        @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "col-md-12" } })
                        @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 phenomena-sm">@Html.LabelFor(model => model.MovieId) :</div>
                    <div class="mb-3 col-md-8 phenomena-sm">
                        @Html.EditorFor(model => model.MovieId, new { htmlAttributes = new { @class = "col-md-12" } })
                        @Html.ValidationMessageFor(model => model.MovieId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 phenomena-sm">@Html.LabelFor(model => model.GenerateRotations):</div>
                    <div class="mb-3 col-md-8 phenomena-sm">
                        @Html.CheckBoxFor(model => model.GenerateRotations, new { htmlAttributes = new { @class = "col-md-12" } })
                        @Html.ValidationMessageFor(model => model.GenerateRotations, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                    <input type="submit" value="Create" class="btn btn-danger pl-5 pr-5 pt-2 pb-2 mt-3 ml-3 phenomena-sm">
            </div>
            <div class="row">
                @Html.ActionLink("Back to List", "Index", "AdminRotations", routeValues: null, htmlAttributes: new { @class = "mt-3 text-link phenomena-sm ml-5" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VivedyWebApp/Views/AdminRotations/Delete.cshtml
@model VivedyWebApp.Models.Rotation

@{
    ViewBag.Title = "Admin | Delete Rotation";
}

@using (Html.BeginForm("Delete", "AdminRotations", null, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()

    <div>
        <div class="containerOneAdmin">
            <div class="white-bg-color mx-auto text-dark " style="max-width: 750px; border: .5rem solid #a8000a;">
                <div class="mb-5 mt-4 phenomena-sm border-bottom border-dark " style="color: #a8000a"><h1 class="display-5">DELETE ROTATION</h1></div>
                <div class="border-bottom">
                    <div class="row">
                        <div class="col-3 phenomena-sm">@Html.DisplayNameFor(model => model.RotationId) : </div>
                        <div class="mb-3 col-md-8 phenomena-sm" readonly>
                            @Html.DisplayFor(model => model.RotationId)
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3 phenomena-sm">@Html.DisplayNameFor(model => model.StartTime) : </div>
                        <div class="mb-3 col-md-8 phenomena-sm" readonly>
                            @{
                                string startTime = Model.StartTime.ToString("dddd, dd MMMM yyyy HH:mm tt");
                                @Html.DisplayFor(model => startTime)
                            }
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3 phenomena-sm">@Html.DisplayNameFor(model => model.MovieId) :</div>
                        <div class="mb-3 col-md-8 phenomena-sm">
                            @Html.DisplayFor(model => model.MovieId)
                        </div>
                    </div>
                </div>
                    <div class="row">
                        <input type="submit" value="Delete" class="btn btn-danger pl-5 pr-5 pt-2 pb-2 mt-3 ml-3 mr-4 phenomena-sm">
                    </div>
                    <div class="row">
                        @Html.ActionLink("Back to List", "Index", "AdminRotations", routeValues: null, htmlAttributes: new { @class = "mt-3 text-link phenomena-sm ml-5" })
                    </div>
                </div>
            
        </div>
    </div>
  }

VivedyWebApp/Views/AdminRotations/Details.cshtml
@model VivedyWebApp.Models.Rotation

@{
    ViewBag.Title = "Admin | Rotation Details";
}

<div class="containerOneAdmin">
    <div class="white-bg-color mx-auto text-dark " style="max-width: 750px; border: 0.5rem solid #a8000a;">
        <div class="mb-5 mt-4 phenomena-sm border-bottom border-dark " style="color: #a8000a"><h1 class="display-5">ROTATION DETAILS</h1></div>
        <div class="border-bottom">
            <div class="row">
                <div class="col-3 phenomena-sm">@Html.DisplayNameFor(model => model.RotationId) : </div>
                <div class="mb-3 col-md-8 phenomena-sm" readonly>
                    @Html.DisplayFor(model => model.RotationId)
                </div>
            </div>
            <div class="row">
                <div class="col-3 phenomena-sm">@Html.DisplayNameFor(model => model.StartTime) : </div>
                <div class="mb-3 col-md-8 phenomena-sm" readonly>
                    @{
                        string startTime = Model.StartTime.ToString("dddd, dd MMMM yyyy HH:mm tt");
                        @Html.DisplayFor(model => startTime)
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-3 phenomena-sm">@Html.DisplayNameFor(model => model.MovieId) :</div>
                <div class="mb-3 col-md-8 phenomena-sm">
                    @Html.DisplayFor(model => model.MovieId)
                </div>
            </div>
        </div>
        <div class="row">
            @Html.ActionLink("Edit", "Edit", "AdminRotations", new { id = Model.RotationId }, new { @class = "btn btn-danger pl-5 pr-5 pt-2 pb-2 mt-3 ml-4 mr-4 phenomena-sm" })
            @Html.ActionLink("Delete", "Delete", "AdminRotations", new { id = Model.RotationId }, new { @class = "btn btn-danger pl-5 pr-5 pt-2 pb-2 mt-3 phenomena-sm"  })
        </div>
        <div class="row">
            @Html.ActionLink("Back to List", "Index", "AdminRotations", routeValues: null, htmlAttributes: new { @class = "mt-3 text-link phenomena-sm ml-5" })
        </div>
    </div>
</div>

VivedyWebApp/Views/AdminRotations/Edit.cshtml
@model VivedyWebApp.Models.Rotation

@{
    ViewBag.Title = "Admin | Edit Rotation";
}

@using (Html.BeginForm("Edit", "AdminRotations", null, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="containerOneAdmin">
        <div class="white-bg-color mx-auto text-dark " style="max-width: 750px; border: .5rem solid #a8000a;">
            <div class="mb-5 mt-4 phenomena-sm border-bottom border-dark " style="color: #a8000a"><h1 class="display-5">EDIT ROTATION</h1></div>
            <div class="border-bottom">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-3 phenomena-sm">@Html.LabelFor(model => model.RotationId) : </div>
                    <div class="mb-3 col-md-8 phenomena-sm">
                        @Html.DisplayFor(model => model.RotationId, new { htmlAttributes = new { @class = "col-md-12" } })
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 phenomena-sm">@Html.LabelFor(model => model.StartTime) : </div>
                    <div class="mb-3 col-md-8 phenomena-sm">
                        @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "col-md-12" } })
                        @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 phenomena-sm">@Html.LabelFor(model => model.MovieId) :</div>
                    <div class="mb-3 col-md-8 phenomena-sm">
                        @Html.EditorFor(model => model.MovieId, new { htmlAttributes = new { @class = "col-md-12" } })
                        @Html.ValidationMessageFor(model => model.MovieId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                    <input value="Save" type="submit" class="btn btn-danger pl-5 pr-5 pt-2 pb-2 mt-3  ml-3 mr-4 phenomena-sm">
            </div>
            <div class="row">
                @Html.ActionLink("Back to List", "Index", "AdminRotations", routeValues: null, htmlAttributes: new { @class = "mt-3 text-link phenomena-sm ml-5" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VivedyWebApp/Views/AdminRotations/Index.cshtml
@model IEnumerable<VivedyWebApp.Models.Rotation>

@{
    ViewBag.Title = "Admin | Rotaions";
}

<div class="adminCard">
    <div class=" mx-auto phenomena-sm display-3 text-center">
        ADMIN ROTATIONS
    </div>
    <div class="white-bg-color">
        <a class="btn btn-danger  phenomena-sm " href="/AdminRotations/Create">ADD <i class="fas fa-plus"></i></a>
        <input type="text" class="mb-3 float-right" id="Search" placeholder="Search by Start Time...">
        <br>
        <table class="table table-striped  phenomena-sm" style="border: 8px solid #a8000a; color: #222;">
            <thead>
                <tr class="text-center ">
                    <th scope="col" >
                        @Html.DisplayNameFor(model => model.RotationId)
                    </th>
                    <th scope="col" >
                        @Html.DisplayNameFor(model => model.StartTime)
                    </th>
                    <th scope="col" class="admin-display-sm-none">
                        @Html.DisplayNameFor(model => model.MovieId)
                    </th>
                    <th scope="col">

                    </th>
                </tr>
            </thead>
            <tbody id="myList">
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="admin-display-cut">
                            @Html.DisplayFor(modelItem => item.RotationId)
                        </td>
                        <td class="startTime admin-display-set-width">
                            @{
                                string startTime = item.StartTime.ToString("dddd, dd MMMM yyyy HH:mm tt");
                                @Html.DisplayFor(modelItem => startTime)
                            }
                        </td>
                        <td class="admin-display-cut admin-display-sm-none">
                            @Html.DisplayFor(modelItem => item.MovieId)
                        </td>
                        <td>
                            <div class="admin-button">
                                @Html.ActionLink("Edit", "Edit", "AdminRotations", routeValues: new { id = item.RotationId }, htmlAttributes: new { @class = "btn btn-danger  phenomena-sm ", style = "font-size: .7rem;" }) |
                                @Html.ActionLink("Details", "Details", "AdminRotations", routeValues: new { id = item.RotationId }, htmlAttributes: new { @class = "btn btn-danger  phenomena-sm ", style = "font-size: .7rem;" }) |
                                @Html.ActionLink("Delete", "Delete", "AdminRotations", routeValues: new { id = item.RotationId }, htmlAttributes: new { @class = "btn btn-danger  phenomena-sm ", style = "font-size: .7rem;" })
                            </div>
                            <div class="admin-button-row">
                                <div class="row">
                                    @Html.ActionLink("Edit", "Edit", "AdminRotations", routeValues: new { id = item.RotationId }, htmlAttributes: new { @class = "btn btn-danger  phenomena-sm ", style = "font-size: .7rem;" })
                                </div>
                                <div class="row">
                                    @Html.ActionLink("Details", "Details", "AdminRotations", routeValues: new { id = item.RotationId }, htmlAttributes: new { @class = "btn btn-danger  phenomena-sm ", style = "font-size: .7rem;" })
                                </div>
                                <div class="row">
                                    @Html.ActionLink("Delete", "Delete", "AdminRotations", routeValues: new { id = item.RotationId }, htmlAttributes: new { @class = "btn btn-danger  phenomena-sm ", style = "font-size: .7rem;" })
                                </div>

                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    let Search;
    let rowslist = Array();

    window.onload = function () {
        Search = document.getElementById("Search");
        Search.oninput = SearchForStartTime;

        rowslist = document.getElementById("myList").getElementsByTagName("tr");
        for (let i = 0; i < rowslist.length; i++) {
            rowslist[i].unmatched = false;
            rowslist[i].startTime = rowslist[i].getElementsByClassName("startTime")[0].innerHTML;
        }
    }
    function SearchForStartTime() {
        for (let i = 0; i < rowslist.length; i++) {
            if (rowslist[i].startTime.indexOf(Search.value) > -1) {
                rowslist[i].unmatched = false;
                rowslist[i].style.display = "";
            }
            else {
                rowslist[i].unmatched = true;
                rowslist[i].style.display = "none";
            }
        };
    }
</script>